#+title: quicklisp-docs

This utility generates documentation for a library after it has been installed with quicklisp.

* Installation

** Lisp Side

Please ensure [[https://www.quicklisp.org/beta/][Quicklisp]] is installed. Then clone this repository into the =local-projects= directory

: git clone https://github.com/rudolfochrist/quicklisp-docs.git ~/quicklisp/local-projects/

Run

: (ql:quickload :quicklisp-docs)

to install =quicklisp-docs=. Also, add the above line to the init file of your CL implementation.

** Emacs Side (optional)

Put

: (load (expand-file-name "~/quicklisp/local-projects/quicklisp-docs/quicklisp-docs.el") t)

in your Emacs init file. Adjust the path to quicklisp accordingly.

* Usage

** Lisp Side

Install libraries with quicklisp as usual

: (ql:quickload :alexandria)

Per default, this installs the documentation under =~/quicklisp/docs/=. This can be customized by setting
=*ql-docs-home*=.

If you don't want to generate documentation for a specific system, then you can add it to the list of excluded
systems like so:

: (ql-docs:exclude-system :cl-ppcre)

** Emacs Side (optional)

To use the documentation for Alexandria (see above) from within =slime-documentation-lookup=, call

: (ql-docs-reload-docs)  ;; <-- this is Emacs Lisp. This will certainly fail in the SLIME REPL.

Example configuration:

#+BEGIN_SRC emacs-lisp
(load (expand-file-name "~/quicklisp/local-projects/quicklisp-docs/quicklisp-docs.el") t)
(setq ql-docs-browser-function #'eww-browse-url)
(ql-docs-reload-docs)
#+END_SRC

If you install a new library during a REPL session, call =ql-docs-reload-docs= again to fetch the new
documentation.

* License

MIT

See [[file:LICENSE][LICENSE]].
